sudo: required

os: linux

language: generic

services:
  - docker

before_install:
  - make up

script:
  - docker-compose -f docker/docker-compose.yml exec php composer create-project symfony/skeleton project
  - docker-compose -f docker/docker-compose.yml exec php curl -f http://nginx:8090 || exit 1

after_success:
  - docker-compose -f docker/docker-compose.yml stop
  - docker-compose -f docker/docker-compose.yml down -v --remove-orphans