sudo: required

os: linux

language: generic

services:
  - docker

before_install:
  - docker-compose -f docker/docker-compose.yml up --build -d

script:
  - docker-compose -f docker/docker-compose.yml exec php composer create-project symfony/skeleton symfony_app
  - docker-compose -f docker/docker-compose.yml exec nginx curl -o debug-nginx.html http://0.0.0.0:80

after_success:
  - docker-compose -f docker/docker-compose.yml stop
  - docker-compose -f docker/docker-compose.yml down -v --remove-orphans