version: "3"
services:
  php:
    image: docfony:php-7.4
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: docfony-php
    volumes:
      - "../:/var/www"
    networks:
      - symfony_dev

  nginx:
    image: docfony:nginx-1.15
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: docfony-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../:/var/www"
    networks:
      - symfony_dev

  mysql:
    image: mysql:8.0
    container_name: docfony-mysql
    ports:
      - "3308:3306"
    volumes:
      - "dev-mysql:/var/lib/mysql"
    env_file:
      - .env
    networks:
      - symfony_dev

  mongo:
      image: mongo:4-bionic
      container_name: docfony-mongo
      ports:
        - "27017:27017"
      volumes:
        - "dev-mongo:/data/db"
        - "dev-mongo-config:/data/configdb"
      networks:
        - symfony_dev

  redis:
    image: redis:5.0
    container_name: docfony-redis
    volumes:
      - "dev-redis:/data"
    networks:
      - symfony_dev

networks:
  symfony_dev:
    driver: bridge

volumes:
  dev-mysql:
  dev-mongo:
  dev-mongo-config:
  dev-redis: